{{- if and .Values.config.gitSync.sshKey .Values.config.gitSync.enabled}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
  name: {{ template "git_sync_ssh_key" . }}
data:
  gitSshKey: {{ .Values.config.gitSync.sshKey | b64enc | quote }}
{{- end }}
