apiVersion: v2
name: cubestore
description: A Helm chart for Cubestore
type: application
version: 0.9.3
appVersion: "0.33.4"
keywords:
  - cube
  - cubejs
  - cubestore
maintainers:
  - email: luc.vauvillier@gmail.com
    name: Luc Vauvillier
sources:
  - https://github.com/cube-js/cube.js
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/gadsme/charts
