{{- if and .Values.exporter.enabled .Values.exporter.statsd.useDefaultMapping }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.exporter.statsd.mappingConfigMapName }}
  labels:
    {{- include "cubestore.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
data:
  {{ .Values.exporter.statsd.mappingConfigMapKey }}: |
    mappings:
      - match: ".+"
        match_type: regex
        name: "$0"
        labels:
          statsd_metric_name: "$0"
{{- end }}
