apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-router" (include "cubestore.fullname" .) }}
  labels:
    {{- include "cubestore.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ printf "%s-router" (include "cubestore.fullname" .) }}
  selector:
    matchLabels:
      app.kubernetes.io/component: router
      {{- include "cubestore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: router
        {{- include "cubestore.selectorLabels" . | nindent 8 }}
        {{- if .Values.commonLabels }}
        {{- toYaml .Values.commonLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.commonAnnotations }}
      annotations:
      {{- toYaml .Values.commonAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "cubestore.router.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      containers:
        - name: cubestore
          {{- if .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.router.httpPort }}
              protocol: TCP
            - name: meta
              containerPort: {{ .Values.router.metaPort }}
              protocol: TCP
            {{- if .Values.router.mysqlPort }}
            - name: mysql
              containerPort: {{ .Values.router.mysqlPort }}
              protocol: TCP
            {{- end }}
            - name: status
              containerPort: {{ .Values.router.statusPort }}
              protocol: TCP
          env:
            {{- include "cubestore.common-env" . | nindent 12 }}
            {{- $fullName := include "cubestore.fullname" . }}
            {{- $headlessServiceName := printf "%s-%s" $fullName "headless" }}
            {{- $workerPort := .Values.workers.port | int }}
            - name: CUBESTORE_SERVER_NAME
              value: {{ printf "%s-router:%d" (include "cubestore.fullname" .) (.Values.router.metaPort | int) }}
            {{- if .Values.router.mysqlPort }}
            - name: CUBESTORE_PORT
              value: {{ .Values.router.mysqlPort | quote }}
            {{- end }}
            - name: CUBESTORE_HTTP_PORT
              value: {{ .Values.router.httpPort | quote }}
            - name: CUBESTORE_META_PORT
              value: {{ .Values.router.metaPort | quote }}
            - name: CUBESTORE_STATUS_PORT
              value: {{ .Values.router.statusPort | quote }}
            {{ if gt (.Values.workers.workersCount | int) 0 }}
            {{- $workers := list }}
            {{- range $e, $i := until ($.Values.workers.workersCount | int) }}
            {{- $workers = append $workers (printf "%s-workers-%d.%s:%d" $fullName $i $headlessServiceName $workerPort) }}
            {{- end }}
            - name: CUBESTORE_WORKERS
              value: {{ join "," $workers | quote }}
            {{- end }}
            - name: CUBESTORE_DATA_DIR
              value: /cube/.cubestore/data
            {{- if and (not .Values.cloudStorage.gcp.bucket) (not .Values.cloudStorage.aws.bucket) (not .Values.cloudStorage.minio.bucket) }}
            - name: CUBESTORE_REMOTE_DIR
              value: /cube/data
            {{- end }}
            {{- if .Values.router.extraEnvVars }}
            {{- include "cubestore.tplvalues.render" (dict "value" .Values.router.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.router.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.router.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.router.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.router.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.router.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.router.livenessProbe.failureThreshold }}
            httpGet:
              path: /livez
              port: status
          {{- else if .Values.router.customLivenessProbe }}
          livenessProbe:
            {{- toYaml .Values.router.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.router.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.router.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.router.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.router.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.router.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.router.readinessProbe.failureThreshold }}
            httpGet:
              path: /readyz
              port: status
          {{- else if .Values.router.customReadinessProbe }}
          readinessProbe:
            {{- toYaml .Values.router.customReadinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.router.resources }}
          resources:
            {{- toYaml .Values.router.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: datadir
              mountPath: /cube/.cubestore/data
            {{- if and (not .Values.cloudStorage.gcp.bucket) (not .Values.cloudStorage.aws.bucket) (not .Values.cloudStorage.minio.bucket) }}
            - name: remotedir
              mountPath: /cube/data
            {{- end }}
        {{- if .Values.exporter.enabled }}
        - name: statsd-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - '--web.listen-address=0.0.0.0:{{ .Values.exporter.service.port }}'
            - --web.telemetry-path={{ .Values.exporter.service.path }}
            - '--statsd.listen-udp=0.0.0.0:{{ .Values.metrics.port }}'
            - --statsd.cache-size={{ .Values.exporter.statsd.cacheSize }}
            - --statsd.event-queue-size={{ .Values.exporter.statsd.eventQueueSize }}
            - --statsd.event-flush-threshold={{ .Values.exporter.statsd.eventFlushThreshold }}
            - --statsd.event-flush-interval={{ .Values.exporter.statsd.eventFlushInterval }}
            - --statsd.mapping-config=/etc/prometheus-statsd-exporter/statsd-mapping.conf
            {{- if .Values.exporter.extraArgs }}
            {{- toYaml .Values.exporter.extraArgs | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.exporter.service.port }}
              protocol: TCP
            {{- if .Values.metrics.port }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: UDP
            {{- end }}
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
          volumeMounts:
            - name: statsd-mapping-config
              mountPath: /etc/prometheus-statsd-exporter
        {{- end }}
      volumes:
      {{- if not .Values.router.persistence.enabled }}
        - name: datadir
          emptyDir: {}
      {{- end }}
      {{- if and (not .Values.cloudStorage.gcp.bucket) (not .Values.cloudStorage.aws.bucket) (not .Values.cloudStorage.minio.bucket) }}
        - name: remotedir
          persistentVolumeClaim:
            claimName: {{ printf "%s-remote-storage" (include "cubestore.fullname" .) }}
      {{- end }}
      {{- if .Values.exporter.enabled }}
        - name: statsd-mapping-config
          configMap:
            name: {{ .Values.exporter.statsd.mappingConfigMapName }}
            items:
              - key: {{ .Values.exporter.statsd.mappingConfigMapKey }}
                path: statsd-mapping.conf
      {{- end }}
      {{- if .Values.router.affinity }}
      affinity:
        {{- toYaml .Values.router.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.router.tolerations }}
      tolerations:
        {{- toYaml .Values.router.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.router.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.router.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.router.spreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.router.spreadConstraints | nindent 8 }}
      {{- end }}

  {{- if .Values.router.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels:
          app.kubernetes.io/component: router
          {{- include "cubestore.selectorLabels" . | nindent 10 }}
        {{- if .Values.router.persistence.annotations }}
        annotations: {{- toYaml .Values.router.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.router.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        {{- if .Values.router.persistence.storageClass }}
        storageClassName: {{ .Values.router.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.router.persistence.size | quote }}
  {{- end }}
